### ISSUE TITLE
Generate random number

### ISSUE THREAD

**Issue by nweedon** [nweedon/COPRE-RaspberryPi-Baremetal#26]
This could be based on the Mersenne Twister: http://en.wikipedia.org/wiki/Mersenne_twister (looks like it's possible with the capabilities we have).

**Comment by Spike71m** [comment]
Added in the random number generator, seems to be working fine. 
The seed is static at the moment but I can look at a good way to seed the system each time we want a new block. I have tried seeding it with a random number from the generator but that doesn't seem to work.
Not 100% sure why but we can look into it tomorrow.

**Comment by Spike71m** [comment]
For the seed for each block use the tick count.
